### ISSUE TITLE
"OSError[Error24] Too many open files: /tmp/tmp7MZp5A" occured after repeat simulation multiple times

### ISSUE THREAD

**Issue by HaoqiSun** [NeuralEnsemble/PyNN#324] opened 2014-09-24 05:16 UTC
Hi Davison,

I need to run a simulation for many time, here is the code:
for i in range(1000):
    setup(...)
    nn = ... # build network
    nn.record()
    run(100.0)
    spike_times = nn.getSpikes()
    end()

After i = 113 (repeat the simulation for 113 times), an error occurs,
Traceback (most recent call last):
  File "train.py", line 126, in <module>
  File "/home/sunhaoqi/PSLcode/PNG_detector.py", line 68, in detect_PNG
  File "/home/sunhaoqi/PSLcode/PNG_detector.py", line 97, in run_simulation
  File "/usr/local/lib/python2.7/dist-packages/pyNN/nest/__init__.py", line 152, in end
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmp7MZp5A'

This error occurs in end(). It seems that too many files are open, without closing them.
Any idea about it?

Thanks a lot,
Haoqi

**Comment by apdavison** [comment] 2015-02-09 10:14
This seems to be a duplicate of #156

**Closed by apdavison** 2015-02-09 10:14 UTC
