### ISSUE TITLE
PyNN 0.12 missing neuroml

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/PyNN#788] opened 2023-09-29 10:08 UTC
File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pyNN/morphology.py", line 11, in <module>
      import neuroml.arraymorph
  ModuleNotFoundError: No module named 'neuroml'

**Comment by Christian-B** [comment] 2023-09-29 10:10
Fixed with https://github.com/NeuralEnsemble/PyNN/commit/89f8faf3aef7dfeee4ae5c70438a0309749d97fa I see

**Comment by pgleeson** [comment] 2023-09-29 10:38
The requirement above is very restrictive on libNeuroML, and would break a number of other neuroml/pynn pipelines. Is this version required due to arraymorph functionality?

Conversation on this with @sanjayankur31 here: https://github.com/NeuralEnsemble/libNeuroML/issues/111

**Comment by apdavison** [comment] 2023-09-29 11:37
Hi @pgleeson - the problem is with the PyTables dependency, which is very difficult to install on Mac OS for ARM processors (see https://github.com/PyTables/PyTables/issues/832 and https://github.com/PyTables/PyTables/pull/1050) (conda, Brew or MacPorts may work, but I'm trying to stick with just `pip install`)

If it's going to break other pipelines, I'll relax the requirement, but it would help if the `tables` dependency could be made optional for libNeuroML.

**Comment by Christian-B** [comment] 2023-09-29 11:42
We at https://github.com/SpiNNakerManchester/sPyNNaker are not bother which version of libNeuroML.
as to the best of our knowledge none of our pipelines depend on it.

I am currently testing an uncapped libNeuroML but using ubuntu and that is passing all tests run so far.
(excluding an unrelated random error)

We would however be disappointed if the version selected makes installing PyNN and therefor sPyNNaker difficult on some platforms.

**Comment by apdavison** [comment] 2023-09-29 12:06
That's a fair point @Christian-B. I think I will make libNeuroML an optional dependency, since it is only needed for some features of the `morphology` module (and of course for the `neuroml` backend).

**Comment by apdavison** [comment] 2023-09-29 16:08
implemented in [533c7c96]

Released as version 0.12.1

**Closed by apdavison** 2023-09-29 16:08 UTC

**Comment by Christian-B** [comment] 2023-09-30 21:37
Thank you 0.12.1 passes the Spynnaker integration tests which detected the original error
