### ISSUE TITLE
EIF_cond_alpha_isfa_ista cell giving different results on NEURON

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/PyNN#559] opened 2018-02-09 10:33 UTC
[This example](https://github.com/OpenSourceBrain/PyNNShowcase/blob/test_eif/PyNN/NeuroMLTest_PyNN0.9.py) produces different results for the EIF_cond_alpha_isfa_ista cell when run on NEURON (green trace):

     python NeuroMLTest_PyNN0.9.py nest -gui

![image](https://user-images.githubusercontent.com/1556687/36022997-d973d5f4-0d82-11e8-8e9f-3804b6e210ed.png)

     python NeuroMLTest_PyNN0.9.py brian -gui

![image](https://user-images.githubusercontent.com/1556687/36023126-5088d6da-0d83-11e8-8ac7-79fc51b05fbb.png)

     python NeuroMLTest_PyNN0.9.py neuron -gui

![image](https://user-images.githubusercontent.com/1556687/36023022-efce8b8c-0d82-11e8-9fe4-dc34070f8f75.png)

NEURON cell model behaviour seems to be highly depend on dt (dt=0.005 used above), whereas NEST and Brian are well behaved with changes to this. NEURON with dt=0.025:

![image](https://user-images.githubusercontent.com/1556687/36023487-92fea642-0d84-11e8-93df-58d0a8e7b19b.png)

**Comment by appukuttan-shailesh** [comment] 2018-02-28 12:49
I have reproduced the problem ([here](https://github.com/appukuttan-shailesh/testData/blob/master/testcode_559_reduced.py)) with a small example. As @pgleeson has pointed out, the NEURON implementation of `EIF_cond_alpha_isfa_ista` seems highly dependent on the timestep, while this correctly isn't so for Brian and NEST:
![brian](https://user-images.githubusercontent.com/24866517/36788320-c235b33e-1c8d-11e8-9497-eec61e92b7e8.png)
![nest](https://user-images.githubusercontent.com/24866517/36788325-c6c590e0-1c8d-11e8-9027-c55fbb201926.png)
![neuron](https://user-images.githubusercontent.com/24866517/36788330-cb45ccf2-1c8d-11e8-92b1-25fd18abee6b.png)
Shall take a closer look to identify the problem. But that apart, shouldn't we also be concerned about the differences (e.g. in peak amplitudes) between the NEST and Brian implementations (and NEURON, once fixed)?

**Comment by apdavison** [comment] 2018-02-28 13:01
There is an open issue for this problem: #266

**Comment by appukuttan-shailesh** [comment] 2018-02-28 14:45
Do we have any leads on this? ... where to start off? 

And,
> shouldn't we also be concerned about the differences (e.g. in peak amplitudes) between the NEST and Brian implementations (and NEURON, once fixed)?

**Comment by apdavison** [comment] 2018-02-28 14:58
I would start by looking at the .mod file that implements the AdExp mechanism for NEURON (https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/neuron/nmodl/adexp.mod). It may be that it can be improved. 

However, it may be that there is a fundamental limitation to splitting the integration between the POINT_PROCESS and the built-in NEURON integration of the compartment, in which case we might get better results implementing AdExp as an ARTIFICIAL_CELL in NMODL. This would then require more work on the pyNN.neuron backend (support for CurrentSources would have to be re-done, in particular) - see #10

I suggest checking out the [NEURON forum](https://neuron.yale.edu/phpBB/index.php) to see if someone else has a good AdEx implementation for NEURON.

Concerning the peak amplitudes, I don't think this is a solvable problem: the exponential term makes this _extremely_ sensitive to differences in integration methods between simulators.

**Comment by apdavison** [comment] 2019-03-14 16:56
closing as a duplicate of #266

**Closed by apdavison** 2019-03-14 16:56 UTC
Labels: NEURON, duplicate
